### ISSUE TITLE
Device Identification (DeviceManager) class

### ISSUE THREAD

**Issue by Ali237** [CMPUT301F24fusion1s/fusion1-events#15]
**Tasks:**

- [x]   Implement DeviceManager class to handle retrieving, storing, and validating device IDs.
- [ ]   Integrate device ID functionality with Firebase to store/retrieve the device information.
- [ ]   Collaborate with the front-end team to ensure the device ID is properly linked with user actions (e.g., joining events).
