### ISSUE TITLE
Firebase Integration (FirebaseManager)

### ISSUE THREAD

**Issue by Ali237** [CMPUT301F24fusion1s/fusion1-events#32]
**Tasks:**

- [ ]    Implement FirebaseManager to abstract the interaction with Firebase for all core data (events, entrants, waitlists, etc.).
- [ ]     Handle CRUD operations for different entities (Event, Entrant, Organizer, etc.).
- [ ]     Ensure that Firebase permissions are set correctly for different user roles.
